contract_version = 1
omnidoc_version = "1.6.1"

[library]
version = "1.6.1"
revision = "v1.6.1"
repository = "https://github.com/wang-borong/omnidoc"
archive_url = "https://github.com/wang-borong/omnidoc/releases/download/v1.6.1/omnidoc-libs-v1.6.1.tar.gz"
checksum_algorithm = "sha256"
checksum_url = "https://github.com/wang-borong/omnidoc/releases/download/v1.6.1/omnidoc-libs-v1.6.1.tar.gz.sha256"
