#!/usr/bin/env python3
"""Generate a deterministic Markdown inventory of project assets."""

from __future__ import annotations

import os
import pathlib


ASSET_DIRS = ("assets", "images")
EXTENSIONS = {
    ".csv",
    ".gif",
    ".jpeg",
    ".jpg",
    ".pdf",
    ".png",
    ".svg",
    ".webp",
}


def human_size(size: int) -> str:
    value = float(size)
    for unit in ("B", "KiB", "MiB", "GiB"):
        if value < 1024 or unit == "GiB":
            return f"{value:.0f} {unit}" if unit == "B" else f"{value:.1f} {unit}"
        value /= 1024
    return f"{size} B"


def collect(root: pathlib.Path):
    rows = []
    for directory_name in ASSET_DIRS:
        directory = root / directory_name
        if not directory.is_dir():
            continue
        for path in sorted(directory.rglob("*")):
            if path.is_file() and path.suffix.lower() in EXTENSIONS:
                rows.append(
                    (
                        path.relative_to(root).as_posix(),
                        path.suffix.lower().lstrip(".").upper(),
                        human_size(path.stat().st_size),
                    )
                )
    return rows


def render(rows) -> str:
    lines = [
        "# Asset index",
        "",
        "This file is generated by the `asset-index` OmniDoc plugin.",
        "",
    ]
    if not rows:
        lines.extend(["No supported assets were found.", ""])
        return "\n".join(lines)
    lines.extend(["| Asset | Type | Size |", "|---|---:|---:|"])
    for asset, kind, size in rows:
        escaped = asset.replace("|", "\\|")
        lines.append(f"| `{escaped}` | {kind} | {size} |")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    root = pathlib.Path(os.environ["OMNIDOC_PROJECT_DIR"]).resolve()
    destination = root / "generated" / "asset-index.md"
    content = render(collect(root))
    if destination.is_file() and destination.read_text(encoding="utf-8") == content:
        return
    destination.parent.mkdir(parents=True, exist_ok=True)
    temporary = destination.with_suffix(".md.tmp")
    temporary.write_text(content, encoding="utf-8")
    temporary.replace(destination)


if __name__ == "__main__":
    main()
